L = 16
J1 = 1.0
J2 = 1.5
J3 = 0.7
Jp = -1.0
kT = 1.9
initial_state = "4by4"
n_mcs = 10000
fast_code = true
measure_energy = true
dump_config = true
n_dump = 10
dump_config_depend_on_order_param = true
dump_period_depend_on_order_param = 100
dump_controlling_parameter = "2by1"
dump_controlling_parameter_begin = 0.05
dump_controlling_parameter_end = 0.7
seed = 0
n_replicas = 4
